spring:
    application:
        name: oms
server:
    port: 5556

## 配置eureka server服务地址
eureka:
    client:
        serviceUrl:
            defaultZone: http://eserver1:6666/eureka/,http://eserver2:6667/eureka/,http://eserver3:6668/eureka/
